spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

# Kakao API 설정 (더미 값)
kakao:
  api:
    key: dummy-kakao-rest-key
    js-key: dummy-kakao-js-key
    send-message-to-me-url: https://dummy.kakao.com

# Google API 설정 (더미 값)  
google:
  api:
    crawling-key: dummy-google-youtube-key
    place-key1: dummy-google-place-key-1
    place-key2: dummy-google-place-key-2
    place-key3: dummy-google-place-key-3
