spring:
  config:
    import:
      - classpath:application-security.yaml
      - classpath:application-youtube.yaml
      - classpath:application-kakao.yaml
      - classpath:application-db.yaml
      - classpath:application-redis.yaml
      - classpath:application-s3.yaml
      - classpath:application-monitoring.yaml
      - optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  application:
    name: ${APP_NAME}
