spring:
  application:
    name: ${APP_NAME}
  profiles:
    include: db, redis, s3, monitoring, security, youtube, kakao
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
---
spring:
  config:
    activate:
      on-profile: local
logging:
  level:
    root: INFO
    team7.inplace: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    root: INFO
    team7.inplace: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    root: ERROR
    team7.inplace: INFO
    org.springframework.web: ERROR
    org.springframework.security: ERROR