name: Frontend CI/CD for main branches
on:
  push:
    branches:
      - '**'
    paths:
      - 'frontend/**'
      - '.github/**'
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint
      - name: Run Prettier
        run: npm run format -- --check
      - name: Run Tests
        run: npm test

  build-and-deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build project
        run: npm run build
        env:
          VITE_KAKAO_JS_KEY: ${{ secrets.VITE_KAKAO_JS_KEY }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Deploy to S3
        run: |
            # 두 버킷에 배포
            aws s3 sync dist/ s3://inplace.my --delete
            aws s3 sync dist/ s3://www.inplace.my --delete
            # CloudFront 캐시 무효화 필수
            aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths "/*"

  sync-fork:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: creates output
        run: sh ./frontend/build.sh
      - name: Pushes to fork repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.VERCEL_PAT }}
        with:
          source-directory: 'output'
          destination-github-username: 'userjmmm'
          destination-repository-name: 'inplace'
          user-email: ${{ secrets.VERCEL_EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main